image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install -g cnpm --registry=https://registry.npm.taobao.org
  - cnpm install
  - npm run dist
  environment:
    name: cisen
    url: http://www.cisen.org
  artifacts:
    paths:
    - public
  only:
  - master
