image: node:4.2.2

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install
  - npm run dist
  environment:
    url: http://www.cisen.org
  artifacts:
    paths:
    - public
  only:
  - master
